# Alacritty configuration matching Ghostty setup
# Place this file at:
# - Linux: ~/.config/alacritty/alacritty.toml
# - macOS: ~/.config/alacritty/alacritty.toml
# - Windows: %APPDATA%\alacritty\alacritty.toml

[env]
TERM = "xterm-256color"

[window]
opacity = 0.92
blur = true
padding = { x = 10, y = 8 }

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }
size = 14.0

[colors]
primary = { background = "#050505", foreground = "#c5c8c6" }

# Normal colors
[colors.normal]
black = "#1d1f21"
red = "#cc6666"
green = "#b5bd68"
yellow = "#f0c674"
blue = "#81a2be"
magenta = "#b294bb"
cyan = "#8abeb7"
white = "#c5c8c6"

# Bright colors
[colors.bright]
black = "#666666"
red = "#d54e53"
green = "#b9ca4a"
yellow = "#e7c547"
blue = "#7aa6da"
magenta = "#c397d8"
cyan = "#70c0b1"
white = "#eaeaea"

[shell]
program = "/opt/homebrew/bin/fish"  # macOS
# program = "/usr/bin/fish"         # Linux
# program = "C:\\tools\\fish\\fish.exe"  # Windows (uncomment if needed)

[keyboard]
bindings = [
    { key = "N", mods = "Command", action = "SpawnNewInstance" },
    { key = "Plus", mods = "Command", action = "IncreaseFontSize" },
    { key = "Minus", mods = "Command", action = "DecreaseFontSize" },
    { key = "Key0", mods = "Command", action = "ResetFontSize" },
]